repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest version
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=5000']  # Replace 500 with your desired max file size in KB
